### ISSUE TITLE
Probably just selection bias

### ISSUE THREAD

**Issue by unrealwill** [seccode/Sha256#1]
I think what you are observing is the selection bias of removing samples from the dataset to make the class have the same number of examples

https://github.com/seccode/Sha256/blob/85dbcb44a17745b7e138ab39025ee1c5ab611491/sha256.py#L24-L36

Before this selection you have 512 hashes that correspond to a "0". 
Then you remove samples so that you have 488 examples of each.

The removed samples are in order so the biggest values are biased towards one of the classes.

This bias is what allows you to make better than average prediction.

One tempting fix would be to apply some permutation to the dataset before selecting. 
```
perm = np.random.permutation(len(y))
x = x[perm,:]
y = list(np.array(y)[perm])
```

But it's not so easy because info leaks. You have a dataset where you have put "holes", and if you can identify which are the "holes" you can make better prediction.

Applying the above trick at every iteration make the predictability go to Predictability: 0.487 which means the opposite predictor would be 0.513 aka the bias, meaning the holes have still been identified.

**Comment by seccode** [comment]
Oh I'm sorry! You should be looking at preimage.py, not sha256. I am continuously changing sha256.py to try different approaches. You're totally right about your point, thanks! I will revert to my last version that wasn't resampling, because I was still seeing statistically significant results there.

**Comment by seccode** [comment]
Actually deleted sha256.py because its not relevant, all that's important here is the preimage vulnerability demonstration.
